sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-search-plugin
    all_branches: true
env:
  global:
  - secure: oMK2weQl/qGs98fXsid2qH/B7gfbFTu6Kdb8y0i+j7wlLBQkeBQmzs15e6+S7ztTGljj9ZI9533wFakEmEwzF9ZGV2sQeAXCXOXrQD2he2CK3veAmYoBwMqvT4WRXtelRRl5SoQQ8gRK7/5fEiOw6Y0lR50O0dlWCjGHcwRyCYjzXP2lWRK7yMGa64NiX8SXFfPhvZtsWWbYu+c4zDubjDgRKmrGY3Icc9kFmM4Y0QyrWEZaD5AxaxVBIQyeYyV+X0M4g0+QBkP2ye5p9zNAjng0iOhbVBi/w/RxS6arqkIhddbBqEnvuD2dwwgsGyoOAAva3RJCDacwOCV7mPqVAkNx05e62r2mn3652coJR0BGpe+HzlEVuK9mvxUt2d08k9gREHmGfK4A7BGJK5Sh3+BHMVtNWUHqAYmSL+h4Ki8HOV6cOWcDSyWFFp3cqkS+8LrhNG7W0i3moSlzVd6xCbt7UzMZcGOA4YIAk7BSd1ij035z0uYjkTshUJOoO2pmNbGK9BRzZq9JhLn286MdZrGVSARrREiO3JohkNpHjIBcfoQ8dU7M8aTSPuJMoRkrYjg+pHEbuSsCWMkyoafVzXBvxfzxZf2+fbE7naGSmqP8is5ZK3z0Htcfc+j+VrWoSIF6eS/wirn45yBNnZRRDd8bCfiQbBTqlAQZ5iYGsF0=
  - secure: PGppTbrKAYyMKHkS+CH6aa4pBiVNUvhtVgapQ06CglXiIRqA3JLwAJOMhtRQb7gwt6SeNYViyqvD2pk4vTYyEoP2ISl432CXW51zzlBbkJX93LnQ7rmkxJuV801Z/D/P2G4Ff3MufbDtYNIcEKQsCfF08WqgbdeDvyGgdzefBQY2/Z2qKPI6fLt336pdx3d0fKrryOi5nMc1UxNovr0OgVekL2wlK6S1TlM1/rch6VTBSst+OOEju/znLT+vR5HB7wZ1v7Cs9maAH7cJXquCCaEjqk04f59+JD2ddsQxUpjBCPzT+orysGr52YzN+Xye4CA3Zl9ibzlH77WrlK0N0dIBNxvbadatbiPrmD6qqJi1tIxMJ7zsJUkgAMtx7IvPOrmefKxCk0qaXwwIjOmNf6rLqImZTKJXziWBBP92O3nInpKfixEW937dokBhXQnlHlDwv0hVHZ0HDTdbqFhSaFJpvlYNX7YV5WsLgKNL8PXa8EWzNzOy+T+R+Gxocwd8icoCfFPOrN9JsLstnbqHvajuDZwPWvTqXn6yKz4aQML/0KnSBI1czIaOiVf/CGVlA35YKygFBTtdv5u8sKxqIuJC0JhGm8e388UDdiwTVZ16VSkLNeDsDDfUlvUtKEfsuZl8UWdb3siAuQh5kydJlfy40RqaMpfZL8ssN+zd5Dc=
